from alpaca.inputs import (
    AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, IAM_INSTANCE_PROFILE, REPO_LOCATION, PATH_TO_OASISLMF_JSON,
    AWS_REGION, OASISLMF_VERSION, OASISLMF_BRANCH, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS, SSH_MAX_RETRIES,
    AWS_PROFILE, DEBUG, RESULT_DIRECTORY
)


REQUIRED_CONFIG_MODEL = [AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, IAM_INSTANCE_PROFILE, REPO_LOCATION, PATH_TO_OASISLMF_JSON]
OPTIONAL_CONFIG_MODEL = [AWS_REGION, OASISLMF_VERSION, OASISLMF_BRANCH, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS,
                         SSH_MAX_RETRIES, AWS_PROFILE, DEBUG, RESULT_DIRECTORY]
