from alpaca.inputs import (
    AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION, PATH_TO_OASISLMF_JSON,
    AWS_REGION, IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS, SSH_MAX_RETRIES
)


REQUIRED_CONFIG_MODEL = [AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION, PATH_TO_OASISLMF_JSON]
OPTIONAL_CONFIG_MODEL = [AWS_REGION, IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS,
                         SSH_MAX_RETRIES]
