# Config: (name, description, default)
AWS_REGION = ("AWS_REGION", "region of EC2 instance to create", "eu-west-1")
AMI_ID = ("AMI_ID", "Amazon Machine ID", "ami-09079da11cd2861fa")
SECURITY_GROUP_ID = ("SECURITY_GROUP_ID", "Security group id of EC2 instance", "MySecurityGroup")
SUBNET_ID = ("SUBNET_ID", "Subnet id of EC2 instance", "MySubnetID")
KEY_NAME = ("KEY_NAME", "Name of key used to create EC2 instance", "key")
KEY_PATH = ("KEY_PATH", "Path to your key", "path/to/key.pem")
REPO_LOCATION = ("REPO_LOCATION", "S3 location (s3://bucket) or link to GitHub repo (https://github.com/name/repo) with data",
                 "https://github.com/OasisLMF/OasisPiWind")
PATH_TO_OASISLMF_JSON = ("PATH_TO_OASISLMF_JSON", "Path from base of REPO_LOCATION to OASISLMF.JSON file", "./oasislmf.json")
INSTANCE_TYPE = ("INSTANCE_TYPE", "Server configuration, amount of resources:", "t3.medium")
DISK_GB = ("DISK_GB", "How many GB your EC2 needs to store your data", "50")
IAM_INSTANCE_PROFILE = ("IAM_INSTANCE_PROFILE", "Instance profile used to allow S3 access", "ProfileName")
OASISLMF_VERSION = ("OASISLMF_VERSION", "Specific version of OasisLMF to use", "")
LOG_LEVEL = ("LOG_LEVEL", "Verbosity of logging", "INFO")
EC2_NAME = ("EC2_NAME", "Name of EC2 Instance", "Alpaca")
RESULT_DIRECTORY = ("RESULT_DIRECTORY", "Where to store results, s3 (s3://bucket) or local (./path/to/local)", "./runs")
PYTEST_ARGS = ("PYTEST_ARGS", "Arguments to pass to PyTest (already uses -vv flag)", "")
PATH_TO_DOCKER_COMPOSE = ("PATH_TO_DOCKER_COMPOSE", "Path from base of REPO_LOCATION to docker-compose file (or bash script)",
                          "./docker-compose.yml")
MAX_LIFETIME_HOURS = ("MAX_LIFETIME_HOURS", "Max lifetime of EC2 instance in hours", "2")
