from alpaca.inputs import (
    AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, IAM_INSTANCE_PROFILE, REPO_LOCATION,
    AWS_REGION, OASISLMF_VERSION, OASISLMF_BRANCH, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, PYTEST_ARGS, MAX_LIFETIME_HOURS,
    SSH_MAX_RETRIES, AWS_PROFILE, DEBUG, RESULT_DIRECTORY
)


REQUIRED_CONFIG_PYTEST = [AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, IAM_INSTANCE_PROFILE, REPO_LOCATION]
OPTIONAL_CONFIG_PYTEST = [AWS_REGION, OASISLMF_VERSION, OASISLMF_BRANCH, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME,
                          PYTEST_ARGS, MAX_LIFETIME_HOURS, SSH_MAX_RETRIES, AWS_PROFILE, DEBUG, RESULT_DIRECTORY]
