from alpaca.config import create_config
from alpaca.inputs import (
    AWS_REGION, AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION,
    IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, PYTEST_ARGS, MAX_LIFETIME_HOURS
)


REQUIRED_CONFIG = [AWS_REGION, AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION]
OPTIONAL_CONFIG = [IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, PYTEST_ARGS, MAX_LIFETIME_HOURS]


def create_pytest_config(args=None):
    create_config(REQUIRED_CONFIG, OPTIONAL_CONFIG)
