from alpaca.config import create_config
from alpaca.inputs import (
    AWS_REGION, AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION, PATH_TO_OASISLMF_JSON,
    IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, PATH_TO_DOCKER_COMPOSE, MAX_LIFETIME_HOURS
)


REQUIRED_CONFIG = [AWS_REGION, AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION, PATH_TO_OASISLMF_JSON, PATH_TO_DOCKER_COMPOSE]
OPTIONAL_CONFIG = [IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS]


def create_api_config(args=None):
    create_config(REQUIRED_CONFIG, OPTIONAL_CONFIG)
