from alpaca.inputs import (
    AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, IAM_INSTANCE_PROFILE, REPO_LOCATION, PATH_TO_OASISLMF_JSON, PATH_TO_DOCKER_COMPOSE,
    AWS_REGION, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS, SSH_MAX_RETRIES, AWS_PROFILE
)


REQUIRED_CONFIG_API = [
    AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, IAM_INSTANCE_PROFILE, REPO_LOCATION, PATH_TO_OASISLMF_JSON, PATH_TO_DOCKER_COMPOSE
]
OPTIONAL_CONFIG_API = [AWS_REGION, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS,
                       SSH_MAX_RETRIES, AWS_PROFILE]
