from alpaca.inputs import (
    AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION, PATH_TO_OASISLMF_JSON, PATH_TO_DOCKER_COMPOSE,
    AWS_REGION, IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS
)


REQUIRED_CONFIG_API = [AMI_ID, SECURITY_GROUP_ID, SUBNET_ID, KEY_NAME, KEY_PATH, REPO_LOCATION, PATH_TO_OASISLMF_JSON, PATH_TO_DOCKER_COMPOSE]
OPTIONAL_CONFIG_API = [AWS_REGION, IAM_INSTANCE_PROFILE, OASISLMF_VERSION, INSTANCE_TYPE, DISK_GB, LOG_LEVEL, EC2_NAME, MAX_LIFETIME_HOURS]
